### ISSUE TITLE
Allow user to pass in YAML keyword args in frontmatter.dump and frontmatter.dumps

### ISSUE THREAD

**Issue by eyeseast** [eyeseast/python-frontmatter#10]
Based on discussion in #9. This would allow a user to export metadata beyond the default types supported by PyYAML, including `set` and `OrderedDict` types. It would also allow better processors, like [pretty-yaml](https://github.com/mk-fg/pretty-yaml).

Proposed usage:

```python
>>> import pyaml
>>> post = frontmatter.loads(text, title="Hello, World")
>>> frontmatter.dumps(post, Dumper=pyaml.PrettyYAMLDumper)
```

Both `dump` and `dumps` need to accept arbitrary keyword arguments, and pass those along to `yaml.dump` (instead of `yaml.safe_dump`, as currently used).

The `Dumper` argument should default to `yaml.SafeDumper` or `yaml.CSafeDumper`. Override that at your own risk.

**Comment by maxgrenderjones** [comment]
Thanks -  this covers my use case perfectly!

**Comment by eyeseast** [comment]
Cool. Just pushed this up to PyPi (and bumped to 0.2.0!). Thanks for all the feedback. Let me know how it works.
