### ISSUE TITLE
How to load a dictionary as frontmatter?

### ISSUE THREAD

**Issue by shivams** [eyeseast/python-frontmatter#106]
There seems to be no straightforward way to load a dictionary as a front-matter. How to achieve this seemingly simple yet important task?

**Comment by eyeseast** [comment]
Tell me more about what you mean. Do you have a dictionary and need to construct a text file with frontmatter?

**Comment by shivams** [comment]
Yes, I need to load a dictionary and then construct a text file with frontmatter having the same content as the dictionary.

Here is a simplified reproduction of the use-case:

```python
dataDict = {'id': 123, 'tag': 'sometag'}

# Trying to parse the dictionary as frontmatter
frontmatter.parse(str(data), handler=JSONHandler())
# Output:
# ({}, "{'id': 123, 'tag': 'sometag'}")

```

As you can see in the output, the dictionary is parsed as "content" and not "metadata".

Furthermore, if I try to print the parsed dictionary as frontmatter, it gets printed as content and not metadata:

```python
post = fm.loads(str(data), handler=JSONHandler())

fm.dumps(post)
# Output:
# "{}\n\n\n{'id': 123, 'tag': 'dfdfdf'}"
```

**Comment by shivams** [comment]
Okay. Here is a way that makes it work using `json` module:

```python
# This does NOT work. Dict is not considered as metadata.
>>> frontmatter.parse(json.dumps(data), handler=JSONHandler())
({}, '{"id": 123, "tag": "sometag"}')

# But, if your indent the json output with 4 spaces, then it DOES WORK! Dict is now considered as metadata.
>>> frontmatter.parse(json.dumps(data, indent=4), handler=JSONHandler())
({'id': 123, 'tag': 'sometag'}, '')

```

Both the above approaches have valid JSON. Yet, only the second works. 

Moreover, it feels like a workaround. Is there a simpler way to parse a dict as frontmatter?

**Comment by eyeseast** [comment]
There is a way to do this. I don't think it's documented, since it wasn't originally an intended use case, but I think other people are using the library this way now:

```python
import frontmatter

data = {"title": "Frontmatter", "link": "https://example.com"}

# this is the object returned by frontmatter.loads
post = frontmatter.Post("This is post content", **data)

# dump it as text
text = frontmatter.dumps(post)

# or export to a file
frontmatter.dump(post, "file.txt")
```

More on the `Post` object: https://python-frontmatter.readthedocs.io/en/latest/api.html#post-objects

Hope that helps.

**Comment by shivams** [comment]
Aaah. That does it!
