### ISSUE TITLE
Allow user to pass a custom dump function to export metadata

### ISSUE THREAD

**Issue by eyeseast** [eyeseast/python-frontmatter#11]
Based on discussion in #9 with @maxgrenderjones. This would allow a user to pass in a custom function to export metadata in `frontmatter.dump` and `frontmatter.dumps`.

For example, use `pyaml.dump` instead of `yaml.safe_dump`. The big question is how to pass in arguments. If you want safe mode with `pyaml.dump`, how do you pass in `safe=True`.

Potential implementations:

**Use a little wrapper function:**

``` python
>>> from somepackage import dumperfunc
>>> frontmatter.dumps(post, dump_func=lambda x: dumperfunc(x, foo=1, bar=2, quux=3))
```

**Forward `kwargs` to `dump_func`:**

``` python
>>> import pyaml
>>> post = frontmatter.loads(text, title="Hello, World")
>>> frontmatter.dumps(post, dump_func=pyaml.dump, **pyaml_kwargs)
```

And then,

``` python
def dumps(post, dump_func, **kwargs):
   kwargs=kwargs.copy() 
   if dump_func==pyaml.dump: # obvs would need to do this in a way that doesn't rely on pyaml being available
       if 'foo' not in kwargs:
          kwargs['foo']='defaultfoo'
          ..snip snip...

   dump_func(post.metadata, **kwargs)
```

Big question: Does this have to output YAML? What if the function is `json.dumps`?

And is there a sane way to handle default arguments (such as safe mode)?

**Comment by eyeseast** [comment]
A thought on handling default arguments: Each function is going to have different defaults that keep it safe and sane. More than I or anyone else will think of right now. But if I'm reading and writing a lot of similar posts, I could keep defaults in a module-level dictionary/registry per function.

Within `frontmatter/__init__.py`:

```python
defaults = {
    # key is the actual function, or maybe its name
    # value is default arguments
    yaml.dump: {
        'Dumper': yaml.SafeDumper,
        'default_flow_style': False
}

# and then dumps needs to check for defaults
def dumps(post, func=None, **kwargs):
    if func is None:
        func = yaml.dump

    for k, v in defaults.get(func, {}).items():
        kwargs.setdefault(k, v)

    metadata = func(post.metadata, **kwargs).strip()
    metadata = u(metadata) # ensure unicode
    return POST_TEMPLATE.format(metadata=metadata, content=post.content).strip()
```

Any function not in `frontmatter.defaults` can be safely passed in with keyword arguments. Any code now relying on `yaml.dump` or `yaml.safe_dump` would work as expected. This would let you use `pyaml.dump` without any extra trouble. Conceivably, you could dump metadata as JSON or something else and set a default encoder or indentation.

**Comment by eyeseast** [comment]
Another, maybe simpler option for this: separate modules for other kinds of frontmatter. For example:

```python
import frontmatter

# load a post with yaml frontmatter
frontmatter.load('yaml.md')

# load a post with json frontmatter
frontmatter.json.load('json.md')

# load toml
frontmatter.toml.load('toml.md')
```

This would keep the core functions uncluttered and build in space for later extensibility.

**Comment by drakeguan** [comment]
My simple response is to use a wrapper, or lambda function, if argument passing is necessary. That makes the world much easier, especially while code tracing or debugging ;)

**Comment by eyeseast** [comment]
Going to call this closed, since it's now possible with a custom handler.
