### ISSUE TITLE
support TOML and JSON frontmatter

### ISSUE THREAD

**Issue by thraxil** [eyeseast/python-frontmatter#14]
I'm working with [Hugo](http://gohugo.io/) content, which in addition to YAML, [supports TOML and JSON frontmatter](http://gohugo.io/content/front-matter/). It's not as widespread as Jekyll, but would be nice to have supported as well.

**Comment by eyeseast** [comment]
Yes, would like to support this. I think the implementation I'd lean toward is what I put in this comment: https://github.com/eyeseast/python-frontmatter/issues/11#issuecomment-74392104

Happy to look at a pull request for this. I've never used Hugo, so I don't know what it needs.

**Comment by thraxil** [comment]
Working on a PR now. Hugo just uses different delimiters to specify the format. So

    ---
    format: yaml
    ---

    +++
    format: toml
    +++

    {
        "format": "json"
    }

That's pretty easy to implement, and that seems to be a convention that a few different static generators use, but it's not a real standard, so it might be troublesome if someone ever does it differently.

On the other hand, `frontmatter.json.load('json.md')` and `frontmatter.toml.load('toml.md')` don't really work very well either for the case where you don't know ahead of time which format you're dealing with (which is exactly the case I'm dealing with).

What I was planning was to add was a delimiter to format mapping that would default to the above but that you could override easily. Something like:

```python
delimiters = {'---': 'yaml', '+++': 'toml'}
post = frontmatter.load(myfile, delimiters=delimiters)```

That breaks down a little for something like the JSON delimiters that Hugo uses where it's '{' and '}', but basically heading somewhere in that direction.

**Comment by eyeseast** [comment]
Cool. Will keep an eye out for the PR. Thanks.

**Comment by eyeseast** [comment]
Finally merged this in with the latest version. There is now a global `handlers` module attribute pointing to various implementations, and a `handlers` module (though it's possible this is a name conflict) where various handlers are defined.
