### ISSUE TITLE
Frontmatter ending with dots

### ISSUE THREAD

**Issue by sergiocorreia** [eyeseast/python-frontmatter#16]
YAML spec allows frontmatter to end with dots, even if it's not widely advertised on Jekyll's website.
http://stackoverflow.com/questions/24917042/jekyll-front-matter-ending-in-dots

Is there a way to support it?

**Comment by eyeseast** [comment]
So, would that look like this?

```yaml
...
title: My post with dots
...
```
Or potentially this?

```yaml
---
title: My post with dots
...
```

**Comment by sergiocorreia** [comment]
Only the second case (it must start with dashes)

See http://yaml.org/spec/current.html
Section 2.2 and 4.3.2

Best,
Sergio

**Comment by eyeseast** [comment]
I don't have any objection to supporting it. If you want to try a pull request, I'll take a look.

**Comment by sergiocorreia** [comment]
Great!
S
