### ISSUE TITLE
Preserve front matter ordering

### ISSUE THREAD

**Issue by virtuald** [eyeseast/python-frontmatter#26]
It's a tricky thing to do with PyYAML, but using http://stackoverflow.com/a/21048064/5483904 it's possible. Once you fix the loader up, the things that stand in the way are:
- `parse` takes in defaults as `**kwargs`, which is automatically a dict. Additionally, you can't specify a custom loader, so you have to set it globally.
- Once you fix that, `Post.__init__` takes the metadata as `**kwargs` yet again, which destroys the ordered dict received by the prior function

I suspect to really do this, one would have to break backwards compat. Here's my hacky way of accomplishing this in case anyone else wants this Right Now:

```
#  Patch yaml first

import collections
import yaml

_mapping_tag = yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG

def dict_representer(dumper, data):
    return dumper.represent_dict(data.items())

def dict_constructor(loader, node):
    loader.flatten_mapping(node)
    return collections.OrderedDict(loader.construct_pairs(node))

try:
    yaml.CSafeDumper.add_representer(collections.OrderedDict, dict_representer)
except ImportError:
    pass

yaml.SafeDumper.add_representer(collections.OrderedDict, dict_representer)
yaml.SafeLoader.add_constructor(_mapping_tag, dict_constructor)

# patch frontmatter second
import frontmatter

def _parse(text, **defaults):
    text = frontmatter.u(text)

    # metadata starts with defaults
    metadata = defaults.copy()

    try:
        _, fm, content = frontmatter.FM_BOUNDARY.split(text, 2)
    except ValueError:
        return metadata, text

    fm = yaml.safe_load(fm)

    if isinstance(fm, dict):
        fm.update(metadata)
        metadata = fm

    return metadata, content.strip()

def _loads(text, **defaults):
    metadata, content = _parse(text, **defaults)
    post = frontmatter.Post(content)
    post.metadata = metadata
    return post

frontmatter.parse = _parse
frontmatter.loads = _loads

```

**Comment by eyeseast** [comment]
What's the advantage of preserving key ordering?

Some of this could be done in a custom handler, if we go in that direction. See #25 and the comments on #24.

**Comment by virtuald** [comment]
For my use case, the frontmatter is primarily edited/created by humans, but every once in awhile I want to edit a bunch of it via scripts. By retaining order, it minimizes the noise in git commits when I do editing via scripts (otherwise it's really difficult to figure out what actually got changed).

**Comment by eyeseast** [comment]
This may be easier in Python 3, since `**kwargs` is passed as an `OrderedDict` instead of plain `dict` (https://www.python.org/dev/peps/pep-0468/). Probably still some work to be done, but if you don't need Python 2, it may be less work.

**Comment by vinniejames** [comment]
I'm also needing to preserve order. I am integrating with [Transifex](https://docs.transifex.com/api/introduction), where they key all of the frontmatter by index. I need to matchup my content keys with theirs.

However, when i do `post.keys()` they occur out of order: `['_template', 'title', '_layout']`
When in fact the Markdown file is ordered:
```
---
_layout: default
_template: page-template
title: Awesome Page
---
```

I am then unable to do the reverse lookup I need against the Transifex version

**Comment by virtuald** [comment]
@vinniejames if you use my hack as posted above, then you can retain order.

**Comment by vinniejames** [comment]
I gave that a try, it doesnt seem to have any effect for me. Ill keep tinkering with it. Thanks @virtuald

**Comment by virtuald** [comment]
Here's a full script that includes the hack: https://github.com/firstwiki/_scripts/blob/master/code_from_gh.py

**Comment by pedromorgan** [comment]
Ok so I came here to file this....

my reasons are..
1 -  were using it in a geotehnical lab,so staff are adding frommatter for classification etc
2 - changes in git, do reordeing is causing some issues with diffs etc

And were stuck on python 2.7 for now with pyqt4 and libs..

**Comment by virtuald** [comment]
Use my hack, you'll be happy. 👍

**Comment by eyeseast** [comment]
I'm happy if anyone has a PR that can solve this. For anything in the core library, updates should be added at the [handler](https://python-frontmatter.readthedocs.io/en/latest/handlers.html) level.

**Comment by hosnas** [comment]
> Use my hack, you'll be happy. +1

@virtuald  How can we use it?

**Comment by dirkcuys** [comment]
I've managed to get order preserving frontmatter! The quick version is:
1. upgrade to python >= 3.7
2. Add `sort_keys=False` to `frontmatter.dump` ie `frontmatter.dump(post, f, sort_keys=False)`

Since python 3.7 insertion order for dicts are maintained (no OrderedDict needed) and since then PyYaml have added the option to not sort keys when dumping. kwargs is passed to handler.export, which is passed to `yaml.dump` and things just work!

**Comment by eyeseast** [comment]
I've added an example showing this, which will live in the codebase:

```python
import frontmatter
from pathlib import Path


def test_load_sorted():
    examples = Path(__file__).parent
    text = (examples / "content" / "sorted.txt").read_text()
    post = frontmatter.loads(text)

    assert frontmatter.dumps(post, sort_keys=False) == text.strip()
```

Hope that helps.

**Comment by pruppert** [comment]
I am trying to use frontmatter for a sublime text plugin that has to run under python 3.3. Is there a recommended way to preserve order under 3.3? I see the solution from @virtuald in the original post but am uncertain where to implement that. Any help is appreciated.
