### ISSUE TITLE
All pypi versions beyond 0.2.1 are not sdists

### ISSUE THREAD

**Issue by jakereps** [eyeseast/python-frontmatter#27]
The versions above 0.2.1 are all binaries built for OS X only. `pip install python-frontmatter` on any machine other than a Mac will fallback to 0.2.1 as that was the last version with a valid source distribution. 

Not entirely sure if it's possible to backport [source distributions](https://docs.python.org/3/distutils/sourcedist.html) to the older/current pypi versions, or if a new version would be required.

Just thought you should know, as there seem to be no other issues open about this. Thanks for the package!

**Comment by eyeseast** [comment]
Oops. Thanks for the heads up. Should be fixed now: https://pypi.python.org/pypi/python-frontmatter/0.3.1#downloads
