### ISSUE TITLE
Support in operator

### ISSUE THREAD

**Issue by rerobins** [eyeseast/python-frontmatter#37]
In order to determine if a key is in the frontmatter metadata I have to use:

```python
'key' in post.metadata
```

Which is confusing because I can then access it via:

```python
post['key']
```

Could this be added for consistency?

**Comment by eyeseast** [comment]
Yes, totally should be there. I think easy to add, too. Just need a `__contains__` method: https://docs.python.org/3/reference/datamodel.html#object.__contains__

Interested in adding a PR?
