### ISSUE TITLE
Was v0.4.3 intended to be released on pip?

### ISSUE THREAD

**Issue by XanderXAJ** [eyeseast/python-frontmatter#40]
I can see [on the releases page](https://github.com/eyeseast/python-frontmatter/releases) that there is a v0.4.3.  However, when I search pip, I can only find 0.4.2:

```
$ python3 -m pip search frontmatter
...
python-frontmatter (0.4.2)  - Parse and manage posts with YAML frontmatter
```

Was v0.4.3 intended to be released on pip?

**Comment by eyeseast** [comment]
Should be. Will fix shortly.

**Comment by eyeseast** [comment]
It's up now https://pypi.org/project/python-frontmatter/0.4.3/
