### ISSUE TITLE
Support for Pandoc flavored YAML front matter

### ISSUE THREAD

**Issue by zengxs** [eyeseast/python-frontmatter#42]
Wanted to see about adding support for Pandoc flavored YAML front matter. That flavor allows use 3 dots (`...`) to ending a YAML front matter.

---

From [YAML specs](http://www.yaml.org/spec/1.2/spec.html#id2760395):
* Three dashes `---` is used to separate directives from document content. This also serves to signal the start of a document if no directives are present.
* Three dots `...` indicate the end of a document without starting a new one, for use in communication channels

**Comment by NGenetzky** [comment]
@zengxs , in theory, this should be possible by using the `YAMLHandler` to instantiate a handler and then use it. Unfortunately, this doesn't work. Since this issue is the answer to the universe :smiley_cat: I might consider creating a PR for it if you had a need for it.

```python
import re
from frontmatter import YAMLHandler
yaml_pandoc_re = re.compile(r'^(?:---)|(?:\.\.\.)$', re.MULTILINE)
handler = YAMLHandler(
    fm_boundary=yaml_pandoc_re, start_delimiter='---', end_delimiter='...',
)
```

**Comment by eyeseast** [comment]
Here's a solution, for anyone still watching this:

```python
class PandocHandler(frontmatter.YAMLHandler):
    START_DELIMITER = "---"
    END_DELIMITER = "..."

    def split(self, text):
        "It's going to take a few passes to split here"
        _, start, text = text.partition(self.START_DELIMITER)
        fm, end, content = text.partition(self.END_DELIMITER)
        return fm, content

post = frontmatter.loads(text, handler=PandocHandler())
```
Pandoc format uses different start and end delimiters, which trips up parsing a bit. To make it work, we need a custom handler that deals with each part separately.

There are probably other ways to solve this, but this will work.
