### ISSUE TITLE
Initialize a new post (and not read from file)

### ISSUE THREAD

**Issue by leejoramo-d51** [eyeseast/python-frontmatter#43]
This took me longer to figure out than it should have. In order to create a new post, pass an empty string to `loads`

`post = frontmatter.loads('')`

I think this should be in the documentation.

**Comment by eyeseast** [comment]
This has come up a couple times. It wasn't something I anticipated anyone doing when I first wrote this, so there isn't an idiomatic way of doing it. You can do `frontmatter.parse()` for the same result, or instantiate a post, `frontmatter.Post('starter content')`. 

It might be worth adding a `frontmatter.create()` method, or something similar.

Can you tell me more about how you're using the newly created posts?

**Comment by leejoramo-d51** [comment]
I am writing a migration process from Microsoft SharePoint. So I am starting with quite dirty HTML pulled from SharePoint, cleaning it, grabbing meta data and saving it as a plan text file with front matter for meta data, and HTML for the content. This is where I am creating the new posts.

The next step will be to push the content into two new CMS systems.

**Comment by eyeseast** [comment]
Ah, ok. I would go with `frontmatter.Post(content, metadata)` in that case. If you don't have either `content` or `metadata` available yet, you can just pass an empty string, `frontmatter.Post('')` and it'll work.

Also, if it helps, `frontmatter.dumps` will accept any object with the right properties: `content` and `metadata`, where `content` is a string and `metadata` is dictionary-like. 

Hope that helps.

**Comment by leejoramo-d51** [comment]
Thanks!
