### ISSUE TITLE
Empty Test "test_json_output"

### ISSUE THREAD

**Issue by NGenetzky** [eyeseast/python-frontmatter#57]
Not sure if you are aware, but you have an empty test: [test.py#L239-L240](https://github.com/eyeseast/python-frontmatter/blob/8b16474a664d9ccf1323fcdb5a245ebe630a2c33/test.py#L239-L240)

**Comment by eyeseast** [comment]
Ah, right. I wrote that an then added the more generalized [sanity tests](https://github.com/eyeseast/python-frontmatter/blob/8b16474a664d9ccf1323fcdb5a245ebe630a2c33/test.py#L159). We can delete that.

**Comment by NGenetzky** [comment]
I saw it when I rebased my PR and it puzzled me for a second. Then after I figured it out I laughed a little.

**Comment by eyeseast** [comment]
Go ahead and kill it in your open PR. It's not hurting anything now.

**Comment by eyeseast** [comment]
Closed in #46
