### ISSUE TITLE
Use content as Beautifulsoup instance

### ISSUE THREAD

**Issue by baruchiro** [eyeseast/python-frontmatter#58]
Hi, I'm using this library, and the first thing that I do after I create an instance of `Post` is 
```python
mypost.content = Beautifulsoup(mypost.content)
```
After that, all my code still run without errors, and I get more functionality in `content`.

So I think that it is a good idea to add a `Beautifulsoup` support.

Direct me and I will implement this.

**Comment by eyeseast** [comment]
Hi. Thanks for the suggestion.

My preference for this library is to keep the dependencies as light as possible. This looks like something that's pretty niche, and easy enough to do without changing the library, so I'd rather leave this as something the user does.

Also, there's no requirement that `post.content` be HTML.

Thank you, though.
