### ISSUE TITLE
Boundaries don't allow for any white space.

### ISSUE THREAD

**Issue by Ryan6795** [eyeseast/python-frontmatter#59]
It would be a good idea to allow trailing white space after the open and close delimiters.

Potential TOML Regex: ^\+{3,}\s*

**Comment by rschuetzler** [comment]
Just ran into this issue today trying to deal with a bunch of old Jekyll posts.

**Comment by Ryan6795** [comment]
> Just ran into this issue today trying to deal with a bunch of old Jekyll posts.

Not that it's the right way but I have just been overriding the regex myself. As the markdown files being used with this are hand written so its likely that white spaces would have been added by the author.

**Comment by eyeseast** [comment]
Happy to have a PR. Here's the line to change: https://github.com/eyeseast/python-frontmatter/blob/master/frontmatter/default_handlers.py#L252. Please include tests.

(I don't use TOML at all, so don't feel super comfortable fixing it myself.)
