### ISSUE TITLE
Why are date strings changed?

### ISSUE THREAD

**Issue by sureshjoshi** [eyeseast/python-frontmatter#61]
Just started using python-frontmatter, and it's great. It allowed me to switch away from some cobbled together code to something much cleaner - and I'm able to comfortably release knowing I can adjust front-matter as it suits me. Kudos! Though, I did have a question that I have no strong opinions on. 

Why are my dates modified automatically from ISO8601? For this project, it doesn't really matter - but it's strange that it happens at all.

    date: 2012-10-11T23:39:45-04:00

becomes

    date: 2012-10-12 03:39:45

**Comment by eyeseast** [comment]
No idea! That's interesting, though. I haven't looked closely at how (or if) YAML parses and stringifies dates, but that's where I'd start.

Glad you like the library.

**Comment by eyeseast** [comment]
Going to chalk this up to YAML's idiosyncrasies. Closing pending further complications.

**Comment by kohane27** [comment]
I'm very confused about the following behavior:

```py
text = """
---
wake_up: 06:20
sleep: 10:00
---
Content
"""

post = frontmatter.loads(text)
print(frontmatter.dumps(post))
```

Result:

```
---
sleep: 600
wake_up: 06:20
---

Content
```
`sleep` is changed completely (but not `wake_up`). The `sleep` value is changed from `10:00` to `600`. 

Config: 
OS: Linux
Python: 3.10.4
python-frontmatter: 1.0.0

Any idea is much appreciated. Thanks!

**Comment by kohane27** [comment]
I tried the js's parser [Markdown YAML metadata parser](https://www.npmjs.com/package/markdown-yaml-metadata-parser) and got the same result. I think I got the YAML format wrong. I quoted the value "10:00" and got the same result back. Thanks!
