### ISSUE TITLE
Mismatch between github and pip

### ISSUE THREAD

**Issue by sylvestre** [eyeseast/python-frontmatter#65]
https://pypi.org/project/python-frontmatter/ says that the latest version is 0.4.5
while 0.5.0 is the latest version on https://github.com/eyeseast/python-frontmatter/releases and 0.4.5 doesn't exist on this url

**Comment by eyeseast** [comment]
Let me see if I can get a release out today. Thanks for the heads up.

**Comment by eyeseast** [comment]
Should be all set. Please test and let me know if there's an issue (or just close this if it's working).

**Comment by eyeseast** [comment]
Going to close this unless there's any objection.

**Comment by sylvestre** [comment]
I was waiting to see if my change sticks or not :)

Thanks for your work, I am using it to build the Firefox documentation.
https://hg.mozilla.org/mozilla-central/file/tip/tools/docs/moztreedocs/__init__.py#l127
https://hg.mozilla.org/mozilla-central/file/tip/tools/docs/Pipfile
(we have some markdown coming form Jekyll)
