### ISSUE TITLE
front matter to the bottom

### ISSUE THREAD

**Issue by klml** [eyeseast/python-frontmatter#67]
Front-matter has some confusing disadvantages for "normal" users who only want to edit the prose. I would like to allow the front matter block at the **bottom** of a document, after the prose. 

This is similar to #22.

**Comment by eyeseast** [comment]
Hi. Very belatedly, you could probably do this pretty easily with a custom handler: https://python-frontmatter.readthedocs.io/en/latest/handlers.html

Something like this (haven't tested it):

```python
class ReverseYAMLHandler(YAMLHandler):
    def split(self, text):
        """
        Split text into frontmatter and content
        """
        content, fm, _ = self.FM_BOUNDARY.split(text, 2)
        return fm, content
```

That assumes a document that looks something like this:

```
Here is your content.

---
title: My title
---
```

Try that and see if it works.
