### ISSUE TITLE
Ending with ...

### ISSUE THREAD

**Issue by moronic** [eyeseast/python-frontmatter#83]
If I end my frontmatter with `...` instead of `---`, parsing doesn't work.

**Comment by moronic** [comment]
Maybe 

```
^[-.]{3,}\s*$
```



would fix it?

**Comment by eyeseast** [comment]
Hi. This came up a while ago. There's an example in [this ticket](https://github.com/eyeseast/python-frontmatter/issues/42) that shows how to create a Pandoc handler which will parse mismatched starting and ending delimiters.
