### ISSUE TITLE
Is nesting/indentation allowed?

### ISSUE THREAD

**Issue by pruppert** [eyeseast/python-frontmatter#85]
My python code is: 
```
post['dog'] = "pug"
frontmatter.dump(post, fileName, sort_keys=False)
```
and this dumps correctly for yaml formatted as following:
```
animals:
dog: pug
```
but the following formats both dump `dog: null`
```
animals:
  dog:
```

```
animals:
- dog:
```
Is there any way to format my yaml frontmatter so this plugin will dump to indented/nested items?

**Comment by eyeseast** [comment]
What does it look like if you dump the YAML directly, like this?

```python
import yaml

yaml.dump("""
animals:
  dog:
""")
```
