### ISSUE TITLE
Addition to read the docs for handlers

### ISSUE THREAD

**Issue by kevindurston21** [eyeseast/python-frontmatter#88]
Hi

Thanks for this useful tool.   I used it a year ago and took some time to work out why TOML would not work... I just used it again and forgot the reason so had to puzzle it out again :-)

Could you add a line in the [Handlers section](https://python-frontmatter.readthedocs.io/en/latest/handlers.html#handlers) on readthedocs.io, stating taht to use the TOMLHandler you need to `pip install toml` as it is a prerequisite for the TOML functionality.

It also looks like the package [toml](https://pypi.org/project/toml/) is not being maintained any more and may affect your project at some point (compliance to toml 1.0 standards perhaps).  [tomli](https://pypi.org/project/tomli/) is being talked about as the current toml package of choice for some but I haven't look deeply into either package.

Thanks

Kevin

**Comment by eyeseast** [comment]
Good call. Will add that. I don't use TOML much, myself, so I'm open to suggestions on the best Python library to handle it.
