### ISSUE TITLE
Quotes strings with incorrect syntax

### ISSUE THREAD

**Issue by willfaught** [eyeseast/python-frontmatter#97]
Say a frontmatter entry is this:

```yaml
title: "MacOS: It's Time To Take The Next Step"
```

This will be serialized as `title: 'MacOS: It's Time To Take The Next Step'`, which isn't valid.

**Comment by eyeseast** [comment]
Looks like it's an issue with PyYAML:

```python
>>> import yaml
>>> fm = '''title: "MacOS: It's Time To Take The Next Step"'''
>>> d = yaml.load(fm, Loader=yaml.SafeLoader)
>>> d
{'title': "MacOS: It's Time To Take The Next Step"}

# this is what frontmatter.dumps does
>>> yaml.dump(d, Dumper=yaml.SafeDumper, default_flow_style=False, allow_unicode=True)
"title: 'MacOS: It''s Time To Take The Next Step'\n"
```

Maybe something about `SafeDumper`?

**Comment by willfaught** [comment]
I think this was my mistake. I think it serialized using the `''` escape for apostrophes, and I later replaced `''` with `'`, which then made the YAML invalid. Sorry for the confusion, and thanks for looking into it.
